name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:

  # -------------------------
  # 1Ô∏è‚É£ Security Job
  # -------------------------
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm audit --audit-level=high
      - run: npm run build

  # -------------------------
  # 2Ô∏è‚É£ Build & Push Job
  # -------------------------
  build:
    needs: security   # üëà Only runs if security succeeds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: docker build -t harikiruthik/myapp:latest .

      - name: Push Image
        run: docker push harikiruthik/myapp:latest

  # -------------------------
  # 3Ô∏è‚É£ Deploy Job
  # -------------------------
  deploy:
    needs: build   # üëà Only runs if build succeeds
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker pull harikiruthik/myapp:latest
            sudo docker run -d \
              -p 80:5173 \
              --restart always \
              --name myapp \
              harikiruthik/myapp:latest
